package edu.kpi.brs.jobfinder.model.job;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import edu.kpi.brs.jobfinder.model.company.Company;
import edu.kpi.brs.jobfinder.model.seeker.SeekerProfile;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * Location generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "location")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Location implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 3935502487022871794L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "location_generator")
    @SequenceGenerator(name = "location_generator", sequenceName = "location_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @Column(name = "city", nullable = false, length = 50)
    private String city;

    @Column(name = "state", nullable = false, length = 50)
    private String state;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
    private Set<JobPost> jobPosts = new HashSet<>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
    private Set<SeekerProfile> seekerProfiles = new HashSet<>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
    private Set<Company> companies = new HashSet<>(0);
}
