package edu.kpi.brs.jobfinder.model.user;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * UserLog generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "user_log")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class UserLog implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 377480831917237267L;

    @GenericGenerator(name = "edu.kpi.brs.jobfinder.model.UserLogIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userAccount"))
    @Id
    @GeneratedValue(generator = "edu.kpi.brs.jobfinder.model.UserLogIdGenerator")
    private int userAccountId;

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private UserAccount userAccount;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "dd.MM.yyyy")
    @Column(name = "last_login_date", nullable = false, length = 13)
    private Date lastLoginDate;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "dd.MM.yyyy")
    @Column(name = "last_job_apply_date", length = 13)
    private Date lastJobApplyDate;
}
