package edu.kpi.brs.jobfinder.model.user;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import edu.kpi.brs.jobfinder.model.job.JobPost;
import edu.kpi.brs.jobfinder.model.job.JobPostActivity;
import edu.kpi.brs.jobfinder.model.seeker.SeekerProfile;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * UserAccount generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "user_account")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class UserAccount implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -9211287032373170847L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_account_generator")
    @SequenceGenerator(name = "user_account_generator", sequenceName = "user_account_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_type_id", nullable = false)
    private UserType userType;

    @Column(name = "email", nullable = false)
    private String email;

    @Column(name = "password", nullable = false, length = 100)
    private String password;

    @Column(name = "is_active", nullable = false)
    private boolean isActive;

    @Column(name = "sms_notification_active", nullable = false)
    private boolean smsNotificationActive;

    @Column(name = "email_notification_active", nullable = false)
    private boolean emailNotificationActive;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "dd.MM.yyyy")
    @Column(name = "registration_date", nullable = false, length = 13)
    private Date registrationDate;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
    private Set<JobPost> jobPosts = new HashSet<>(0);

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "userAccount")
    private UserLog userLog;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
    private Set<JobPostActivity> jobPostActivities = new HashSet<>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userAccount")
    private Set<SeekerProfile> seekerProfiles = new HashSet<>(0);
}
