package edu.kpi.brs.jobfinder.model.company;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import edu.kpi.brs.jobfinder.model.job.JobPost;
import edu.kpi.brs.jobfinder.model.job.Location;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * Company generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "company")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Company implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 899121659928964185L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "company_generator")
    @SequenceGenerator(name = "company_generator", sequenceName = "company_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "business_stream_id", nullable = false)
    private BusinessStream businessStream;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "employee_amount_id", nullable = false)
    private EmployeeAmount employeeAmount;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location_id", nullable = false)
    private Location location;

    @Column(name = "company_name", nullable = false, length = 100)
    private String companyName;

    @Column(name = "headline", nullable = false, length = 200)
    private String headline;

    @Column(name = "description", nullable = false, length = 1000)
    private String description;

    @Column(name = "company_website", nullable = false, length = 200)
    private String companyWebsite;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "dd.MM.yyyy")
    @Column(name = "establishment_date", nullable = false, length = 13)
    private Date establishmentDate;

    @Column(name = "contact_number", nullable = false, length = 20)
    private String contactNumber;

    @Column(name = "email", nullable = false)
    private String email;

    @Column(name = "company_detail", nullable = false, length = 4000)
    private String companyDetail;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
    private Set<JobPost> jobPosts = new HashSet<>(0);
}
