package edu.kpi.brs.jobfinder.model.company;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * EmployeeAmount generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "employee_amount")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class EmployeeAmount implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -3091664260952153721L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "employee_amount_generator")
    @SequenceGenerator(name = "employee_amount_generator", sequenceName = "employee_amount_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @Column(name = "amount", nullable = false, length = 30)
    private String amount;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeAmount")
    private Set<Company> companies = new HashSet<>(0);
}
