package edu.kpi.brs.jobfinder.model.seeker;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * ExperienceDetail generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "experience_detail")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class ExperienceDetail implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1358482387847077696L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "experience_detail_generator")
    @SequenceGenerator(name = "experience_detail_generator", sequenceName = "experience_detail_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @Column(name = "start_date", nullable = false, length = 13)
    private Date startDate;

    @Column(name = "end_date", nullable = false, length = 13)
    private Date endDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seeker_id", nullable = false)
    private SeekerProfile seekerProfile;

    @Column(name = "company_name", nullable = false, length = 100)
    private String companyName;

    @Column(name = "position", nullable = false, length = 100)
    private String position;

    @Column(name = "description", length = 4000)
    private String description;

    @Column(name = "is_current_job", nullable = false)
    private boolean isCurrentJob;

    @Column(name = "image_path", length = 200)
    private String imagePath;
}
