package edu.kpi.brs.jobfinder.model.seeker;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.springframework.util.AutoPopulatingList;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import edu.kpi.brs.jobfinder.model.job.Location;
import edu.kpi.brs.jobfinder.model.user.UserAccount;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * SeekerProfile generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "seeker_profile")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class SeekerProfile implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -484188740322077849L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seeker_profile_generator")
    @SequenceGenerator(name = "seeker_profile_generator", sequenceName = "seeker_profile_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "currency_id", nullable = false)
    private Currency currency;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "location_id", nullable = false)
    private Location location;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_account_id", nullable = false)
    private UserAccount userAccount;

    @Column(name = "first_name", nullable = false, length = 50)
    private String firstName;

    @Column(name = "last_name", nullable = false, length = 50)
    private String lastName;

    @Column(name = "headline", nullable = false, length = 200)
    private String headline;

    @Column(name = "description", nullable = false, length = 4000)
    private String description;

    @Column(name = "website", nullable = false, length = 50)
    private String website;

    @Column(name = "salary")
    private Integer salary;

    @Column(name = "is_annually_monthly")
    private Boolean isAnnuallyMonthly;

    @Column(name = "age", nullable = false)
    private int age;

    @Column(name = "contact_number", nullable = false, length = 20)
    private String contactNumber;

    @Column(name = "resume_path", length = 200)
    private String resumePath;

    @Column(name = "image_path", length = 200)
    private String imagePath;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seekerProfile")
    private List<EducationDetail> educationDetails = new AutoPopulatingList<>(EducationDetail.class);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seekerProfile")
    private Set<SeekerSkillSet> seekerSkillSets = new HashSet<>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seekerProfile")
    private Set<ExperienceDetail> experienceDetails = new HashSet<>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seekerProfile")
    private Set<SeekerTag> seekerTags = new HashSet<>(0);
}
