package edu.kpi.brs.jobfinder.model.seeker;
// Generated 22.06.2018 15:44:18 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

/**
 * SeekerSkillSet generated by hbm2java
 */
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table(name = "seeker_skill_set")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class SeekerSkillSet implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -1637638297742808878L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seeker_skill_set_generator")
    @SequenceGenerator(name = "seeker_skill_set_generator", sequenceName = "seeker_skill_set_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    private int id;

    @Column(name = "seeker_id", nullable = false)
    private int seekerId;

    @Column(name = "skill_set_id", nullable = false)
    private int skillSetId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seeker_id", nullable = false, insertable = false, updatable = false)
    private SeekerProfile seekerProfile;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "skill_set_id", nullable = false, insertable = false, updatable = false)
    private SkillSet skillSet;

    @Column(name = "skill_level", nullable = false)
    private int skillLevel;
}
